language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python-dev
    - cmake

before_install:
  - export CXX=g++-4.8
  - export CC=gcc-4.8

install:
  - pip3 install -r requirements.txt

script:
  - python3 setup.py develop
  #- pytest --ignore="setup.py" --ignore="read_fasta.py" --doctest-modules --cov=pypcpe2 -v -s
  - nosetests --detailed-errors --with-doctest -v
