language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake
  - pip install -r requirements.txt

script:
  - python setup.py develop
  - nosetests --detailed-errors --with-doctest -v
