language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

install:
  - docker build -t yen3/pypcpe2-test .

script:
  - docker run --rm yen3/pypcpe2-test
  - echo ${TRAVIS_PYTHON_VERSION}
